CREATE TABLE PERSON(id int, name varchar(30), age int);

INSERT INTO PERSON VALUES(1, 'HENRY', 18);
INSERT INTO PERSON VALUES(2, 'SARAH', 28);
INSERT INTO PERSON VALUES(3, 'JOE', 33);

SELECT * FROM PERSON;